pub mod challenge_1_1;
pub mod challenge_1_2;
pub mod challenge_2_1;
pub mod challenge_2_2;
pub mod challenge_3_1;
pub mod challenge_3_2;
pub mod challenge_4_1;
pub mod challenge_4_2;
pub mod challenge_5_1;
